[package]
name = "influx-line"
version = "1.0.0"
edition = "2021"
authors = ["Invian"]
license-file = "LICENSE"

[dependencies]
derive_more = "0.99"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1"

[dev-dependencies]
rstest = "0.21"
